# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Alinx/Alinx7010/Self_learning/ov5640_mnist/ov5640_mnist.srcs/sources_1/ip/float_fix/float_fix.xci
# IP: The module: 'float_fix' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Alinx/Alinx7010/Self_learning/ov5640_mnist/ov5640_mnist.srcs/sources_1/ip/float_fix/float_fix_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_fix'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Alinx/Alinx7010/Self_learning/ov5640_mnist/ov5640_mnist.srcs/sources_1/ip/float_fix/float_fix.xci
# IP: The module: 'float_fix' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Alinx/Alinx7010/Self_learning/ov5640_mnist/ov5640_mnist.srcs/sources_1/ip/float_fix/float_fix_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_fix'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
