# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Alinx/Alinx7010/Self_learning/ov5640_mnist/ov5640_mnist.srcs/sources_1/ip/b1_blkmem/b1_blkmem.xci
# IP: The module: 'b1_blkmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Alinx/Alinx7010/Self_learning/ov5640_mnist/ov5640_mnist.srcs/sources_1/ip/b1_blkmem/b1_blkmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'b1_blkmem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Alinx/Alinx7010/Self_learning/ov5640_mnist/ov5640_mnist.srcs/sources_1/ip/b1_blkmem/b1_blkmem.xci
# IP: The module: 'b1_blkmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Alinx/Alinx7010/Self_learning/ov5640_mnist/ov5640_mnist.srcs/sources_1/ip/b1_blkmem/b1_blkmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'b1_blkmem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
