# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_serial/ov5640_mnist_serial.srcs/sources_1/ip/fcnnb_blkmem/fcnnb_blkmem.xci
# IP: The module: 'fcnnb_blkmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_serial/ov5640_mnist_serial.srcs/sources_1/ip/fcnnb_blkmem/fcnnb_blkmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fcnnb_blkmem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_serial/ov5640_mnist_serial.srcs/sources_1/ip/fcnnb_blkmem/fcnnb_blkmem.xci
# IP: The module: 'fcnnb_blkmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_serial/ov5640_mnist_serial.srcs/sources_1/ip/fcnnb_blkmem/fcnnb_blkmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fcnnb_blkmem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
