# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.cache/wt [current_project]
set_property parent.project_path D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/Alinx/Alinx7010/Self_learning/ov5640_mnist/repo [current_project]
set_property ip_output_repo d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/imports/ov5640_mnist/sigmoid.coe
add_files D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/imports/ov5640_mnist/fcnn_W.coe
add_files d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/fcnn_b.coe
add_files d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/five.coe
add_files d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/W1.coe
add_files d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/W2.coe
add_files d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/b1.coe
add_files d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/b2.coe
add_files d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/batch_normalization.coe
add_files d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/fcnn_W.coe
read_verilog -library xil_defaultlib {
  D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/imports/src/alinx_ov5640.v
  D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/new/batch_normalization.v
  D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/imports/src/cmos_8_16bit.v
  D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/imports/new/convlayer.v
  D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/imports/pooling/max2to1.v
  D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/imports/pooling/max_pooling.v
  D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/imports/pooling/max_pooling_1serial.v
  D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/imports/pooling/max_pooling_core.v
  D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/new/mnist_256to1pix.v
  D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/new/mnist_process.v
  D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/new/out_select.v
  D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/new/out_select_cell.v
  D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/imports/pooling/pooling_ctrl.v
  D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/new/red_block.v
  D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/new/sigmoid.v
  D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/new/single_convcore.v
  D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/hdl/system_wrapper.v
}
add_files D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_150M_0/system_rst_processing_system7_0_150M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_150M_0/system_rst_processing_system7_0_150M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_150M_0/system_rst_processing_system7_0_150M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_axis_subset_converter_0_1/system_axis_subset_converter_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/bd/system/system_ooc.xdc]

read_ip -quiet D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/float_div/float_div.xci
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/float_div/float_div_ooc.xdc]

read_ip -quiet D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/fcnnb_blkmem/fcnnb_blkmem.xci
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/fcnnb_blkmem/fcnnb_blkmem_ooc.xdc]

read_ip -quiet D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/rgb2dvi_hdmi/rgb2dvi_hdmi.xci
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/rgb2dvi_hdmi/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/rgb2dvi_hdmi/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/rgb2dvi_hdmi/src/rgb2dvi_clocks.xdc]

read_ip -quiet D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/mnist_image_blkmem/mnist_image_blkmem.xci
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/mnist_image_blkmem/mnist_image_blkmem_ooc.xdc]

read_ip -quiet D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/W1_blkmem/W1_blkmem.xci
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/W1_blkmem/W1_blkmem_ooc.xdc]

read_ip -quiet D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/W2_blkmem/W2_blkmem.xci
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/W2_blkmem/W2_blkmem_ooc.xdc]

read_ip -quiet D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/fcnnW_blkmem/fcnnW_blkmem.xci
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/fcnnW_blkmem/fcnnW_blkmem_ooc.xdc]

read_ip -quiet D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/b1_blkmem/b1_blkmem.xci
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/b1_blkmem/b1_blkmem_ooc.xdc]

read_ip -quiet D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/b2_blkmem/b2_blkmem.xci
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/b2_blkmem/b2_blkmem_ooc.xdc]

read_ip -quiet D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/BN_blkmem/BN_blkmem.xci
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/BN_blkmem/BN_blkmem_ooc.xdc]

read_ip -quiet D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/sigmoid_blkmem/sigmoid_blkmem.xci
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/sigmoid_blkmem/sigmoid_blkmem_ooc.xdc]

read_ip -quiet D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/conv_ram/conv_ram.xci
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/conv_ram/conv_ram_ooc.xdc]

read_ip -quiet D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/pooling_ram/pooling_ram.xci
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/pooling_ram/pooling_ram_ooc.xdc]

read_ip -quiet D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/classify_ram/classify_ram.xci
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/classify_ram/classify_ram_ooc.xdc]

read_ip -quiet D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/fix_float/fix_float.xci
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/fix_float/fix_float_ooc.xdc]

read_ip -quiet D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/float_fix/float_fix.xci
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/float_fix/float_fix_ooc.xdc]

read_ip -quiet D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/fcnnW_buffer/fcnnW_buffer.xci
set_property used_in_implementation false [get_files -all d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/fcnnW_buffer/fcnnW_buffer_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/constrs_1/new/system.xdc
set_property used_in_implementation false [get_files D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/constrs_1/new/system.xdc]

read_xdc D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/constrs_1/new/hdmi_out.xdc
set_property used_in_implementation false [get_files D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/constrs_1/new/hdmi_out.xdc]

read_xdc D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/constrs_1/new/an5642.xdc
set_property used_in_implementation false [get_files D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/constrs_1/new/an5642.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb"
