# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/test_imgrom/test_imgrom.xci
# IP: The module: 'test_imgrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/test_imgrom/test_imgrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_imgrom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/test_imgrom/test_imgrom.xci
# IP: The module: 'test_imgrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Alinx/Alinx7010/Self_learning/ov5640_mnist_parallel/ov5640_mnist_parallel.srcs/sources_1/ip/test_imgrom/test_imgrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_imgrom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
